/**
 * Icon system.
 *
 * The app draws its icons from its own set — 208 drawings on a 24x24 grid,
 * 1.5 stroke, two colour layers. It replaced Tabler, which had replaced
 * Phosphor; both packages are gone from package.json.
 *
 * This module stays a COMPATIBILITY LAYER, not a re-export list. It keeps the
 * call signature the app already uses:
 *
 *   - the same export names the ~297 consumer files import;
 *   - a `weight` prop that is ACCEPTED AND IGNORED, so the ~2,300
 *     `weight="fill"|"bold"|"regular"` props across the app keep compiling;
 *   - `size`, `mirrored`, `color` and every other SVG prop, unchanged.
 *
 * Several names map to one drawing where the old set carried redundant
 * variants — Spinner / SpinnerGap / CircleNotch are one spinner now.
 *
 * Eleven exports that no file imported were dropped in this pass: Browser,
 * CaretLineLeft, DeviceMobileCamera, Equalizer, MicrophoneSlash, MusicNotes,
 * PhoneSlash, SimCard, SpeakerSlash, Vault. (Download stayed; it is aliased.)
 *
 * GENERATED — do not hand-edit. See ./svg/README.md.
 */
export type { Icon, IconProps, IconWeight } from "./types";

export {
  Archive,
  ArrowBendUpLeft,
  Refresh as ArrowClockwise,
  RotateCcw as ArrowCounterClockwise,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ExternalLink as ArrowSquareOut,
  ArrowUp,
  ArrowUpRight,
  Refresh as ArrowsClockwise,
  ArrowsDownUp,
  ArrowsIn as ArrowsInSimple,
  ArrowsLeftRight,
  ArrowsOut,
  ArrowsOut as ArrowsOutSimple,
  Bank,
  Barcode,
  Notificacoes as Bell,
  BellSlash,
  Bookmark,
  BracketsAngle,
  BracketsCurly,
  Brain,
  Broadcast,
  Buildings,
  Calculator,
  Agenda as Calendar,
  Agenda as CalendarBlank,
  CalendarCheck,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  CaretUpDown,
  Certificate,
  Relatorios as ChartBar,
  ChartDonut,
  ChartLine,
  TrendUp as ChartLineUp,
  ChartPie,
  Mensagens as ChatCenteredDots,
  Mensagens as ChatCircle,
  Mensagens as ChatCircleDots,
  Mensagens as ChatTeardropDots,
  ChatText,
  Chats as ChatsCircle,
  Check,
  Sucesso as CheckCircle,
  Checks,
  Circle,
  Spinner as CircleNotch,
  ClipboardText,
  Clock,
  Timer as ClockCountdown,
  History as ClockCounterClockwise,
  Code,
  Command,
  Confetti,
  Copy,
  Copy as CopySimple,
  Crown,
  Crown as CrownSimple,
  Financeiro as CurrencyDollar,
  Cursor,
  CursorClick,
  Database,
  Monitor as Desktop,
  DeviceMobile,
  DragHandle as DotsSixVertical,
  DotsThree,
  DotsThree as DotsThreeOutline,
  DotsThreeVertical,
  Exportar as Download,
  Exportar as DownloadIcon,
  Exportar as DownloadSimple,
  Envelope,
  Envelope as EnvelopeSimple,
  Visualizar as Eye,
  EyeSlash as EyeClosedIcon,
  EyeSlash,
  Filtros as Faders,
  Documentos as File,
  FileCsv,
  Documentos as FileText,
  Files,
  FilmSlate,
  FilmStrip,
  Fire,
  Flag as FlagCheckered,
  Save as FloppyDisk,
  FlowArrow,
  Funil as Funnel,
  Funil as FunnelSimple,
  Configuracoes as Gear,
  Configuracoes as GearSix,
  Gif,
  GitBranch,
  GitMerge,
  Globe,
  Globe as GlobeHemisphereWest,
  Globe as GlobeSimple,
  Google as GoogleLogo,
  GraduationCap,
  Dashboard as GridFour,
  Handshake,
  Hash,
  Suporte as Headset,
  Heart,
  Hourglass,
  Hourglass as HourglassMedium,
  IdCard as IdentificationBadge,
  IdCard as IdentificationCard,
  Image,
  ImageBroken,
  Image as ImageSquare,
  Informacao as Info,
  Instagram as InstagramLogo,
  Receipt as Invoice,
  Kanban,
  Key,
  Leaf,
  Lightbulb,
  Lightning,
  Link,
  LinkBreak,
  Link as LinkSimple,
  LinkBreak as LinkSimpleBreak,
  Menu as List,
  Menu as ListBullets,
  Menu as ListDashes,
  ListNumbers,
  Lock,
  Lock as LockIcon,
  LockKey,
  Buscar as MagnifyingGlass,
  MapPin,
  Megaphone,
  Microphone,
  Minus,
  Monitor,
  MonitorPlay,
  Moon,
  Editar as NotePencil,
  Package,
  PaintBrush,
  Palette,
  PaperPlane as PaperPlaneRight,
  PaperPlane as PaperPlaneTilt,
  Paperclip,
  Pause,
  PauseCircle,
  Editar as Pencil,
  Editar as PencilSimple,
  Usuarios as Person,
  Phone,
  PhoneCall,
  PhoneDisconnect,
  PhoneIncoming,
  PhoneOutgoing,
  Pix as PixLogo,
  Play,
  PlayCircle,
  Plug,
  Plugs,
  Plugs as PlugsConnected,
  Plus,
  Adicionar as PlusCircle,
  Power,
  Prohibit,
  Pulse,
  PuzzlePiece,
  Ajuda as Question,
  Queue,
  Receipt,
  Robot,
  Scales,
  Sucesso as SealCheck,
  Shield,
  ShieldCheck,
  ShieldPlus,
  ShieldWarning,
  Shuffle,
  SignIn,
  SignOut,
  Siren,
  Filtros as Sliders,
  Filtros as SlidersHorizontal,
  Smiley,
  SmileyMeh,
  SmileySad,
  SmileyWink,
  Sparkle,
  SpeakerHigh,
  Spinner,
  Spinner as SpinnerGap,
  Square,
  Dashboard as SquaresFour,
  Stack,
  Star,
  Stop,
  StopCircle,
  Storefront,
  Subset as SubsetProperOfIcon,
  Sun,
  Table,
  Tag,
  TagChevron,
  Tag as TagSimple,
  Oportunidades as Target,
  Telegram as TelegramLogo,
  TestTube,
  TextT as TextAa,
  TextAlignLeft,
  TextBold as TextB,
  TextH1 as TextHOne,
  TextH3 as TextHThree,
  TextH2 as TextHTwo,
  TextItalic,
  TextT,
  Thermometer as ThermometerSimple,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Excluir as Trash,
  Excluir as TrashSimple,
  TreeStructure,
  TrendUp,
  Importar as Upload,
  Importar as UploadSimple,
  Usuarios as User,
  UserCheck,
  Usuarios as UserCircle,
  Leads as UserCirclePlus,
  UserGear,
  UserMinus,
  Leads as UserPlus,
  Clientes as Users,
  Clientes as UsersFour,
  Clientes as UsersThree,
  VideoCamera as Video,
  VideoCamera,
  Wallet,
  Alerta as Warning,
  Atencao as WarningCircle,
  WaveSquare,
  Waveform,
  Webhooks as WebhooksLogo,
  Whatsapp as WhatsappLogo,
  Wifi as WifiHigh,
  Wifi as WifiMedium,
  WifiSlash,
  Wrench,
  Fechar as X,
  XCircle,
} from "./glyphs";
